CREATE TABLE IF NOT EXISTS ebooks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  regular_price DECIMAL(10,2) DEFAULT 0,
  offer_price DECIMAL(10,2) DEFAULT 0,
  thumbnail VARCHAR(255),
  pdf VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
